# Site Settings
title: SYSTEMLIFE
email: commisori28@gmail.com
description: linux system life
baseurl: "/jekflix-template" # the subpath of your site, e.g. /blog
url: "https://dongdongjoo.github.io" # the base hostname & protocol for your site
google_analytics: "UA-114756867-1"

# User Settings
username: DongDongJu
user_description: fall in love with computer science.

# Social Media
# Remove the item if you don't need it
github_username: DongDongJu

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# Plugins
gems:
  - jemoji

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: About
    url: /about/
  - title: Contact
    url: /contact/

# Exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
